const carFunctionalitiesAndAccessories = [
  // Functionalities
  'Air conditioning',
  'Heating',
  'Power steering',
  'Anti-lock braking system (ABS)',
  'Traction control',
  'Electronic stability control (ESC)',
  'Cruise control',
  'Adaptive cruise control',
  'Parking assist',
  'Rearview camera',
  '360-degree camera',
  'Lane departure warning system',
  'Blind-spot monitoring',
  'Automatic emergency braking (AEB)',
  'Collision avoidance system',
  'Keyless entry',
  'Push-button start',
  'Adaptive headlights',
  'Automatic high beams',
  'Rain-sensing wipers',
  'Auto-dimming rearview mirror',
  'Wireless charging pad',
  'Driver drowsiness detection',
  'Voice control system',
  'Auto-parking system',
  'Hybrid engine',
  'Electric engine',
  'Four-wheel drive (4WD)',
  'All-wheel drive (AWD)',
  'Turbocharged engine',
  'Tow hitch',
  'Fog lights',
  'Moonroof/Sunroof',
  'Convertible top',

  // Accessories
  'Roof rack',
  'Cargo carrier',
  'Trailer hitch',
  'Bike rack',
  'Kayak rack',
  'Ski rack',
  'Cargo net',
  'Car cover',
  'Floor mats',
  'Seat covers',
  'Steering wheel cover',
  'Car organizer',
  'Dash cam',
  'Bluetooth adapter',
  'Phone mount',
  'USB charger',
  'Auxiliary cable',
  'Tire pressure gauge',
  'Emergency kit',
  'First aid kit',
  'Car air freshener',
  'Window tint',
  'Windshield sunshade',
  'GPS navigation system',
  'Backseat entertainment system',
];

const options = carFunctionalitiesAndAccessories.map(el => {
  return {
    label: el,
    value: el,
  };
});

export default options;
